name: deploy customer-portal

on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/onegridxyz/customer-portal-deploy/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "sha": "'"${{ github.sha }}"'" }}'
